wisp:
  parent_id: 3219980361
  test_type: integration
openapi-fdr:
  parent_id: 3250356236
checkout-e2e:
  parent_id: 3235250264
  test_type: e2e
qa_hub_apis:
  latest_suite_version:
    url: https://api.uat.platform.pagopa.it/qa/central-hub/v1/api/v1/test-metrics/test-suites/latest/
    method: GET
    api_key: $APIM_QA_HUB_KEY
  save_test_suite:
    url: https://api.uat.platform.pagopa.it/qa/central-hub/v1/api/v1/test-metrics/test-suites
    method: POST
    api_key: $APIM_QA_HUB_KEY
  save_test_runs:
    url: https://api.uat.platform.pagopa.it/qa/central-hub/v1/api/v1/test-metrics/test-runs
    method: POST
    api_key: $APIM_QA_HUB_KEY
  save_test_executions:
    url: https://api.uat.platform.pagopa.it/qa/central-hub/v1/api/v1/test-metrics/test-executions
    method: POST
    api_key: $APIM_QA_HUB_KEY
