SECRET_PATH: "./config/.secrets.yaml"
TARGET_ENV: "uat"
services:
  nodo_per_pa:
    url: "https://api.uat.platform.pagopa.it/nodo-auth/nodo-per-pa/v1"
    subscription_key: "FORWARDER_SUBSCRIPTION_KEY"
  node_for_psp:
    url: "https://api.uat.platform.pagopa.it/nodo/node-for-psp/v1"
    subscription_key: "NODO_SUBSCRIPTION_KEY"
  nodo_per_pm_v1:
    url: "https://api.uat.platform.pagopa.it/nodo/nodo-per-pm/v1"
    subscription_key: "NODO_SUBSCRIPTION_KEY"
  nodo_per_pm_v2:
    url: "https://api.uat.platform.pagopa.it/nodo/nodo-per-pm/v2"
    subscription_key: "TEST_NODO_SUBSCRIPTION_KEY"
  gpd_core:
    url: "https://api.uat.platform.pagopa.it/gpd/api/v2"
    subscription_key: "GPD_SUBSCRIPTION_KEY"
    healthcheck: "/info"
  wisp_converter:
    url: "https://uat.wisp2.pagopa.it/wisp-converter/redirect/api/v1"
    healthcheck: "/info"
  technical_support:
    url: "https://api.uat.platform.pagopa.it/technical-support/wisp-converter/api/v1"
    subscription_key: "TECHNICAL_SUPPORT_SUBSCRIPTION_KEY"
    healthcheck: "/info"

global_configuration:
  psp_wisp: "AGID_01"
  psp_wfesp: "CIPBITMM"
  psp_broker_wisp: "97735020584"
  psp_broker_wfesp: "13212880150"
  channel_wisp: "97735020584_02"
  channel_wfesp: "13212880150_90"
  channel_checkout: "97735020584_03"
  psp_payment: "BCITITMM"
  psp_name: "Intesa Sanpaolo S.p.A"
  psp_broker_payment: "00799960158"
  channel_payment: "00799960158_07"
  creditor_institution: "15376371009"
  creditor_institution_iban: "IT76P0306909790100000300089"
  creditor_institution_multibeneficiary: "77777777777"
  creditor_institution_multibeneficiary_iban: "IT30N0103076271000001823603"
  creditor_institution_multibeneficiary_2: "99999000013"
  creditor_institution_multibeneficiary_2_iban: "IT60X05428111010000001111111"
  creditor_institution_broker: "15376371009"
  station: "15376371009_09"
  station_gpd: "15376371009_48"

test_data:
  creditor_institution_broker: "<creditor_institution_broker>"
  creditor_institution: "<creditor_institution>"
  station: "<station>"
  station_password: "<station_password>"
  station_gpd: "<station_gpd>"
  station_gpd_password: "<station_gpd_password>"
  psp_wisp: "<psp_wisp>"
  psp_wfesp: "<psp_wfesp>"
  psp_broker_wisp: "<psp_broker_wisp>"
  psp_broker_wfesp: "<psp_broker_wfesp>"
  channel_wisp: "<channel_wisp>"
  channel_wisp_password: "<channel_wisp_password>"
  channel_wfesp: "<channel_wfesp>"
  channel_wfesp_password: "<channel_wfesp_password>"
  channel_checkout: "<channel_checkout>"
  channel_checkout_password: "<channel_checkout_password>"
  psp_payment: "<psp_payment>"
  psp_name: "<psp_name>"
  psp_broker_payment: "<psp_broker_payment>"
  channel_payment: "<channel_payment>"
  payer:
    type: "F"
    fiscal_code: "VRDMRN92A12H501Z"
    name: "Marina Verdi"
    email: "marina.verdi@mail.com"
    address: "Via della Conciliazione"
    address_number: "1"
    address_zipcode: "00100"
    address_location: "Roma"
    address_province: "RM"
    address_nation: "IT"
  payer_delegate:
    type: "F"
    fiscal_code: "RSSMRA70A01H501Z"
    name: "Maria Rossi"
    email: "maria.rossi@mail.com"
    address: "Via della Conciliazione"
    address_number: "1"
    address_zipcode: "00100"
    address_location: "Roma"
    address_province: "RM"
    address_nation: "IT"
    iban: "IT12A1234512345123456789012"
    bic: "ARTIITM1045"
  payee_institutions_1:
    fiscal_code: "15376371009"
    name: "PagoPA S.p.A"
    operative_code: "123"
    operative_denomination: "XXX"
    address: "Piazza Colonna"
    address_number: "370"
    address_zipcode: "00187"
    address_location: "Roma"
    address_province: "RM"
    address_nation: "IT"
    iban: "<creditor_institution_iban>"
    bic: "ARTIITM1050"
  payee_institutions_2:
    fiscal_code: "<creditor_institution_multibeneficiary>"
    name: "EC_TE S.p.A"
    operative_code: "123"
    operative_denomination: "XXX"
    address: "Corso Italia"
    address_number: "1"
    address_zipcode: "00187"
    address_location: "Roma"
    address_province: "RM"
    address_nation: "IT"
    iban: "<creditor_institution_multibeneficiary_iban>"
    bic: "ARTIITM1045"
  payee_institutions_3:
    fiscal_code: "<creditor_institution_multibeneficiary_2>"
    name: "EC DEMO"
    operative_code: "123"
    operative_denomination: "XXX"
    address: "via Roma"
    address_number: "1"
    address_zipcode: "00187"
    address_location: "Roma"
    address_province: "RM"
    address_nation: "IT"
    iban: "<creditor_institution_multibeneficiary_2_iban>"
    bic: "ARTIITM1045"