Feature: User pays a single payment from existing payment position via nodoInviaRPT

  Scenario: : before start
    Given systems up


@runnable @nodo_invia_rpt @test
  Scenario: User pays a single payment with single transfer and no stamp on nodoInviaRPT that exists already in GPD
    Given a single RPT of type BBT with 1 transfers of which 0 are stamps
    And an existing payment position related to first RPT with segregation code equals to 48 and state equals to VALID
    When the execution of "Send a nodoInviaRPT request" was successful
    Then the execution of "Execute redirect and complete payment from NodoInviaRPT" was successful
#    And the execution of "Check if existing debt position was used" was successful

#COMMON
  Scenario: Send a nodoInviaRPT request
    Given a valid nodoInviaRPT request
    When the user sends a nodoInviaRPT action
    Then the user receives the HTTP status code 200
    And the response contains the field esito with value OK
    And the response contains the redirect URL

  Scenario: Execute redirect and complete payment from NodoInviaRPT
    When the execution of "Execute NM1-to-NMU conversion in wisp-converter" was successful
    Then the execution of "Retrieve all related notice numbers from executed redirect" was successful
#    And the execution of "Send a checkPosition request" was successful
#    And the execution of "Send one or more activatePaymentNoticeV2 requests" was successful
#    And the execution of "Check if WISP session timers were created" was successful
#    And the execution of "Send a closePaymentV2 request" was successful
#    And the execution of "Check if WISP session timers were deleted and all RTs were sent" was successful
#    And the execution of "Check the paid payment positions" was successful

  Scenario: Check if existing debt position was used
    Given a waiting time of 2 seconds to wait for Nodo to write RE events
    And the first IUV code of the sent RPTs
    When the user searches for flow steps by IUVs
    Then the user receives the HTTP status code 200
    And there is a redirect event with field status with value UPDATED_EXISTING_PAYMENT_POSITION_IN_GPD

  Scenario: Send a checkPosition request
    Given a valid checkPosition request
    When the creditor institution sends a checkPosition action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field positionslist as not empty list

  Scenario: Check if WISP session timers were created
    Given a waiting time of 5 seconds to wait for Nodo to write RE events
    And all the IUV codes of the sent RPTs
    When the user searches for flow steps by IUVs
    Then the user receives the HTTP status code 200
    And there is a timer-set event with field operationStatus with value Success
    And these events are related to each payment token

  Scenario: Send a closePaymentV2 request
    Given a valid closePaymentV2 request with outcome OK
    When the creditor institution sends a closePaymentV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK

  Scenario: Check if WISP session timers were deleted and all RTs were sent
    Given a waiting time of 10 seconds to wait for Nodo to write RE events
    And all the IUV codes of the sent RPTs
    When the user searches for flow steps by IUVs
    Then the user receives the HTTP status code 200
    Then there is a timer-delete event with field status with value RECEIPT_TIMER_GENERATION_DELETED_SCHEDULED_SEND
    And these events are related to each payment token
    Then there is a receipt-ok event with field status with value RT_SEND_SUCCESS
    And these events are related to each notice number
#FINE COMMON


#Execute redirect and complete payment from NodoInviaRPT
  Scenario: Execute NM1-to-NMU conversion in wisp-converter
    Given a valid session identifier to be redirected to WISP dismantling
    When the user continue the session in WISP dismantling
    Then the user receives the HTTP status code 302
    And the user can be redirected to Checkout

  Scenario: Retrieve all related notice numbers from executed redirect
    Given a waiting time of 2 seconds to wait for Nodo to write RE events
    Given the first IUV code of the sent RPTs
    When the user searches for flow steps by IUVs
    Then the user receives the HTTP status code 200
#    And all the related notice numbers can be retrieved

  Scenario: Send one or more activatePaymentNoticeV2 requests
    # executing 'activation' on first payment notice generated by GPD (not necessarely related only to first RPT!)
    Given a valid activatePaymentNoticeV2 request on first payment notice
    When the creditor institution sends a activatePaymentNoticeV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field paymentToken with non-null value
    And the payment token can be retrieved and associated to first RPT
    # executing 'activation' on second payment notice generated by GPD, if exists
    Given a valid activatePaymentNoticeV2 request on second payment notice
    When the creditor institution sends a activatePaymentNoticeV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field paymentToken with non-null value
    And the payment token can be retrieved and associated to second RPT
    # executing 'activation' on third payment notice generated by GPD, if exists
    Given a valid activatePaymentNoticeV2 request on third payment notice
    When the creditor institution sends a activatePaymentNoticeV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field paymentToken with non-null value
    And the payment token can be retrieved and associated to third RPT
    # executing 'activation' on fourth payment notice generated by GPD, if exists
    Given a valid activatePaymentNoticeV2 request on fourth payment notice
    When the creditor institution sends a activatePaymentNoticeV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field paymentToken with non-null value
    And the payment token can be retrieved and associated to fourth RPT
    # executing 'activation' on fifth payment notice generated by GPD, if exists
    Given a valid activatePaymentNoticeV2 request on fifth payment notice
    When the creditor institution sends a activatePaymentNoticeV2 action
    Then the creditor institution receives the HTTP status code 200
    And the response contains the field outcome with value OK
    And the response contains the field paymentToken with non-null value
    And the payment token can be retrieved and associated to fifth RPT

  Scenario: Check the paid payment positions
    # executing the check on payment position for first IUV
    When the user searches for payment position in GPD by first IUV
    Then the user receives the HTTP status code 200
    And the response contains the field status with value PAID
    And the response contains a single payment option
    And the response contains the payment option correctly generated from first RPT
    And the response contains the status in PO_PAID for the payment option
    And the response contains the transfers correctly generated from RPT
    # executing the check on payment position for second IUV
    When the user searches for payment position in GPD by second IUV
    Then the user receives the HTTP status code 200
    And the response contains the field status with value PAID
    And the response contains a single payment option
    And the response contains the payment option correctly generated from second RPT
    And the response contains the status in PO_PAID for the payment option
    And the response contains the transfers correctly generated from RPT
    # executing the check on payment position for third IUV
    When the user searches for payment position in GPD by third IUV
    Then the user receives the HTTP status code 200
    And the response contains the field status with value PAID
    And the response contains a single payment option
    And the response contains the payment option correctly generated from third RPT
    And the response contains the status in PO_PAID for the payment option
    And the response contains the transfers correctly generated from RPT
    # executing the check on payment position for fourth IUV
    When the user searches for payment position in GPD by fourth IUV
    Then the user receives the HTTP status code 200
    And the response contains the field status with value PAID
    And the response contains a single payment option
    And the response contains the payment option correctly generated from fourth RPT
    And the response contains the status in PO_PAID for the payment option
    And the response contains the transfers correctly generated from RPT
    # executing the check on payment position for fifth IUV
    When the user searches for payment position in GPD by fifth IUV
    Then the user receives the HTTP status code 200
    And the response contains the field status with value PAID
    And the response contains a single payment option
    And the response contains the payment option correctly generated from fifth RPT
    And the response contains the status in PO_PAID for the payment option
    And the response contains the transfers correctly generated from RPT










