uat:
  GPD_SUBSCRIPTION_KEY: <GPD_SUBSCRIPTION_KEY>
  NODO_SUBSCRIPTION_KEY: <NODO_SUBSCRIPTION_KEY>
  NUOVA_CONNETTIVITA_SUBSCRIPTION_KEY: <NUOVA_CONNETTIVITA_SUBSCRIPTION_KEY>
  TECHNICAL_SUPPORT_SUBSCRIPTION_KEY: <TECHNICAL_SUPPORT_SUBSCRIPTION_KEY>
  CHANNEL_WISP_PASSWORD: <CHANNEL_WISP_PASSWORD>
  CHANNEL_WFESP_PASSWORD: <CHANNEL_WFESP_PASSWORD>
  CHANNEL_CHECKOUT_PASSWORD: <CHANNEL_CHECKOUT_PASSWORD>
  CHANNEL_PAYMENT_PASSWORD: <CHANNEL_PAYMENT_PASSWORD>
  STATION_PASSWORD: <STATION_PASSWORD>
