#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const {
  REPO_ROOT, loadProjectConfig, enabledPlatforms, assertSafeWritePath,
} = require('./lib/playbook');

const ROLES = {
  reflector: {
    description: 'Use when: process accumulated ACE traces in batch and produce evidence-backed proposals without editing playbooks.',
    delegates: ['curator'],
    guardrails: [
      'Read the complete trace batch and write only structured proposals.',
      'Never edit playbooks directly and delegate only when the configured threshold is reached.',
    ],
    cycle: 'Read the source prompt, update counters, process the complete batch, and write the proposal artifact.',
  },
  curator: {
    description: 'Use when: turn reflector proposals into typed playbook decisions without applying them.',
    delegates: ['warden'],
    guardrails: [
      'Work only from proposals and traceable evidence.',
      'Never edit playbooks or bypass the deterministic gate and human sign-off.',
    ],
    cycle: 'Read the source prompt, evaluate every proposal, and write typed decisions for the warden.',
  },
  warden: {
    description: 'Use when: run the ACE gate and apply approved decisions one explicit human-confirmed step at a time.',
    delegates: [],
    guardrails: [
      'Never sign or apply a playbook change without the required explicit human confirmation.',
      'If the interactive question tool is unavailable, stop rather than simulating consent.',
    ],
    cycle: 'Read the source prompt, run the unsigned gate, present its result, request each confirmation, and verify every command output.',
  },
};

function relLink(fromFile, toFile) {
  let relative = path.relative(path.dirname(fromFile), toFile).replace(/\\/g, '/');
  if (!relative.startsWith('.')) relative = `./${relative}`;
  return relative;
}

function runtimeName(platform, role) {
  return `${platform.runtime_prefix}/ace/${role}`;
}

function targetFile(platformName, platform, role) {
  const file = platformName === 'copilot'
    ? `ACE-${role}.agent.md`
    : `Ace-${role}.md`;
  return path.join(REPO_ROOT, platform.agents_dir, file);
}

function render(platformName, platform, role) {
  const definition = ROLES[role];
  const target = targetFile(platformName, platform, role);
  const source = path.join(REPO_ROOT, 'ace', 'prompts', `${role}.md`);
  const readInstruction = platformName === 'claude'
    ? 'use `Read` on the complete prompt'
    : 'use `view` or the runtime-compatible file-reading tool on the complete prompt';
  const delegates = definition.delegates.map((delegate) => runtimeName(platform, delegate));
  const lines = [
    '---',
    `name: ${JSON.stringify(runtimeName(platform, role))}`,
    `description: ${JSON.stringify(definition.description)}`,
  ];
  if (platform.model) lines.push(`model: ${JSON.stringify(platform.model)}`);
  lines.push(`tools: [${platform.tools[role].map((tool) => JSON.stringify(tool)).join(', ')}]`);
  if (delegates.length) lines.push(`agents: [${delegates.map((delegate) => JSON.stringify(delegate)).join(', ')}]`);
  lines.push('user-invocable: true', '---', '');
  lines.push(
    '<!-- Generated by ace/scripts/generate_ace_agents.js. Edit ace/prompts instead. -->',
    '',
    `- Source persona: [ace/prompts/${role}.md](${relLink(target, source)}); before acting, ${readInstruction}.`,
    '- The source persona owns the workflow, output contract, and gates. Do not duplicate or replace them here.',
    '',
    '## Non-delegable guardrails',
    ...definition.guardrails.map((item) => `- ${item}`),
    '',
    '## Minimum cycle',
    `1. ${definition.cycle}`,
    `2. Follow the complete source contract${delegates.length ? ` and use only these declared delegates: ${delegates.join(', ')}` : ''}.`,
    '3. Report actual results, blockers, and checks. Never simulate tools or outcomes.',
    '',
  );
  return lines.join('\n');
}

function run({ checkOnly = false } = {}) {
  const config = loadProjectConfig();
  const changes = [];
  const enabled = enabledPlatforms(config);
  const enabledNames = new Set(enabled.map((platform) => platform.name));
  for (const [platformName, platform] of Object.entries(config.platforms || {})) {
    if (enabledNames.has(platformName)) continue;
    for (const role of Object.keys(ROLES)) {
      const target = targetFile(platformName, platform, role);
      if (!fs.existsSync(target)) continue;
      const content = fs.readFileSync(target, 'utf8');
      if (!content.includes('Generated by ace/scripts/generate_ace_agents.js')) continue;
      changes.push(path.relative(REPO_ROOT, target).replace(/\\/g, '/'));
      if (!checkOnly) fs.unlinkSync(target);
    }
  }
  for (const platform of enabled) {
    for (const role of Object.keys(ROLES)) {
      const target = targetFile(platform.name, platform, role);
      assertSafeWritePath(target);
      const content = render(platform.name, platform, role);
      const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
      if (existing === content) continue;
      changes.push(path.relative(REPO_ROOT, target).replace(/\\/g, '/'));
      if (!checkOnly) {
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, content);
      }
    }
  }
  console.log(changes.length
    ? `${checkOnly ? 'Would change' : 'Generated'}: ${changes.join(', ')}`
    : 'No ACE wrapper changes required.');
  return changes;
}

if (require.main === module) {
  try {
    const checkOnly = process.argv.includes('--check');
    const changes = run({ checkOnly });
    if (checkOnly && changes.length) process.exitCode = 1;
  } catch (error) {
    console.error(`ACE wrapper generation failed: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = { ROLES, runtimeName, render, run };
