name: Deploy Integration Reports

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      skipArtifacts:
        description: 'Skip test report artifacts and regenerate only the landing page'
        required: false
        type: boolean

jobs:
  deploy_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch (source)
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages branch in subfolder
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: gh-pages
          path: public

      - name: Download all report artifacts
        if: github.event.inputs.skipArtifacts != 'true'
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          path: artifacts

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install jinja2 requests

      - name: Create timestamp
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d-%Hh%M%S')" >> $GITHUB_ENV

      - name: Process reports with Python
        run: python3 .github/scripts/process_reports.py
        env:
          SKIP_ARTIFACTS: ${{ github.event.inputs.skipArtifacts }}
          TIMESTAMP: ${{ env.timestamp }}

      - name: Copy Landing Page
        run: |
          cp .github/html/index.html public/index.html
          touch public/.nojekyll

      - name: Replace last update date in landing page
        run: sed -i "s/{{LAST_UPDATE_DATE}}/$(date +'%Y-%m-%d')/" public/index.html

      - name: Deploy to GitHub Pages using peaceiris
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Notify Slack with Integration Test Results
        run: python3 .github/scripts/notify_slack.py
        env:
          SLACK_QA_WEBHOOK_URL: ${{ secrets.SLACK_INTEGRATION_TEST_WEBHOOK_URL }}
          TIMESTAMP: ${{ env.timestamp }}
