name: Deploy Integration Reports

on:
  workflow_call:

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: public

      - name: Checkout source branch (landing page + templates)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: source

      - name: Download WISP report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report-wisp
          path: allure-report-wisp
        continue-on-error: true

      - name: Download FdR report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report-fdr
          path: allure-report-fdr
        continue-on-error: true

      - name: Create timestamp
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d-%Hh%M')" >> $GITHUB_ENV

      - name: Copy WISP report
        if: success() || failure()
        run: |
          mkdir -p public/wisp-tests/${{ env.timestamp }}
          cp -r allure-report-wisp/. public/wisp-tests/${{ env.timestamp }}/ || true

      - name: Copy FdR report
        if: success() || failure()
        run: |
          mkdir -p public/fdr-tests/${{ env.timestamp }}
          cp -r allure-report-fdr/. public/fdr-tests/${{ env.timestamp }}/ || true

      - name: Cleanup old WISP reports
        run: |
          cd public/wisp-tests

          valid_dirs=$(ls -dt */ | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}h[0-9]{2}/$' | head -n 30)
          keep_dirs="$valid_dirs last-history/"

          for dir in */; do
            keep=false
            for k in $keep_dirs; do
              if [[ "$dir" == "$k" ]]; then
                keep=true
                break
              fi
            done
            if [[ "$keep" == "false" ]]; then
              echo "Elimino cartella WISP non valida o vecchia: $dir"
              rm -rf "$dir"
            fi
          done

          cd -

      - name: Cleanup old FdR reports
        run: |
          cd public/fdr-tests

          valid_dirs=$(ls -dt */ | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}h[0-9]{2}/$' | head -n 30)
          keep_dirs="$valid_dirs last-history/"

          for dir in */; do
            keep=false
            for k in $keep_dirs; do
              if [[ "$dir" == "$k" ]]; then
                keep=true
                break
              fi
            done
            if [[ "$keep" == "false" ]]; then
              echo "Elimino cartella FdR non valida o vecchia: $dir"
              rm -rf "$dir"
            fi
          done

          cd -

      - name: Generate WISP history page
        run: |
          mkdir -p public/wisp-tests
          cp source/templates/history-index-template.html public/wisp-tests/index.html

          reports_html=""
          for dir in $(ls -dt public/wisp-tests/*/ | grep -v '/last-history/' | grep -v '/index.html' | head -n 30); do
            d=$(basename "$dir")
            reports_html+="<div class=\"col-md-4\"><div class=\"card\"><div class=\"card-body text-center\"><h5 class=\"card-title\">$d</h5><a href=\"./$d/index.html\" class=\"btn btn-primary mt-2\">Visualizza Report</a></div></div></div>"
          done

          sed -i "s|{{ REPORTS }}|$reports_html|" public/wisp-tests/index.html

      - name: Generate FdR history page
        run: |
          mkdir -p public/fdr-tests
          cp source/templates/history-index-template.html public/fdr-tests/index.html

          reports_html=""
          for dir in $(ls -dt public/fdr-tests/*/ | grep -v '/last-history/' | grep -v '/index.html' | head -n 30); do
            d=$(basename "$dir")
            reports_html+="<div class=\"col-md-4\"><div class=\"card\"><div class=\"card-body text-center\"><h5 class=\"card-title\">$d</h5><a href=\"./$d/index.html\" class=\"btn btn-primary mt-2\">Visualizza Report</a></div></div></div>"
          done

          sed -i "s|{{ REPORTS }}|$reports_html|" public/fdr-tests/index.html

      - name: Copy Landing Page
        run: |
          cp source/landing-page/index.html public/index.html
          touch public/.nojekyll

      - name: Replace last update date in landing page
        run: |
          sed -i "s/{{LAST_UPDATE_DATE}}/$(date +'%Y-%m-%d')/" public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
