name: Deploy Integration Reports

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      skipArtifacts:
        description: 'Skip test report artifacts and regenerate only the landing page'
        required: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout full repository (default branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages branch in subfolder
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: public

      - name: Download all report artifacts
        if: github.event.inputs.skipArtifacts != 'true'
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create timestamp
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d-%Hh%M%S')" >> $GITHUB_ENV

      - name: Process reports with Python
        run: |
          pip install jinja2
          python3 .github/scripts/process_reports.py
        env:
          SKIP_ARTIFACTS: ${{ github.event.inputs.skipArtifacts }}
          TIMESTAMP: ${{ env.timestamp }}

      - name: Copy Landing Page
        run: |
          cp landing-page/index.html public/index.html
          touch public/.nojekyll

      - name: Replace last update date in landing page
        run: |
          sed -i "s/{{LAST_UPDATE_DATE}}/$(date +'%Y-%m-%d')/" public/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Slack with Integration Test Results
        run: |
          pip install requests
          python3 .github/scripts/notify_slack.py
        env:
          SLACK_QA_WEBHOOK_URL: ${{ secrets.SLACK_QA_WEBHOOK_URL }}
