name: Build Doc pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: python:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install behave mkdocs-material

      - name: Build Docs
        run: |
          python3 scenario_parser.py --repo-name test --page-name "PagoPA platform integration test"
          mkdocs build

      - name: Upload to GitHub pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          keep_files: true
