name: Build Doc pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b #v5.3.0
        with:
          python-version: 3.x
      - run: python3 --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install behave mkdocs-material

      - name: Build Docs
        run: |
          python3 scenario_parser.py --repo-name ${{ github.event.repository.name }} --page-name "PagoPA platform integration test"
          mkdocs gh-deploy --force
