name: Main Dispatch Integration Tests

on:
  schedule:
    - cron: '17 6 * * *'
    
  workflow_dispatch:
    inputs:
      services:
        description: "Select which services to test"
        required: true
        type: choice
        default: all
        options:
          - wisp
          - openApi_fdr
          # - fdr
          - all

jobs:
  trigger_wisp:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.services == 'wisp' || github.event.inputs.services == 'all'
    uses: ./.github/workflows/wisp-tests.yml
    secrets: inherit

  # trigger_fdr:
  #   if: |
  #     github.event_name == 'schedule' ||
  #     github.event.inputs.services == 'fdr' || github.event.inputs.services == 'all'
  #   uses: ./.github/workflows/fdr-tests.yml
  #   secrets: inherit

  trigger_openApi_fdr:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.services == 'openApi_fdr' || github.event.inputs.services == 'all'
    uses: ./.github/workflows/openApi_test.yml
    secrets: inherit

  deploy:
    if: always()
    needs: [trigger_wisp, trigger_openApi_fdr]
    uses: ./.github/workflows/deploy-test-report.yml
    secrets: inherit
