name: Main Dispatch Integration Tests

on:
  schedule:
    - cron: '0 7 * * *'
    
  workflow_dispatch:
    inputs:
      services:
        description: "Select which services to test"
        required: true
        type: choice
        default: all
        options:
          - wisp
          - fdr
          - all

jobs:
  trigger_wisp:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.services == 'wisp' || github.event.inputs.services == 'all'
    uses: ./.github/workflows/wisp-tests.yml
    secrets: inherit

  trigger_fdr:
    if: |
      github.event_name == 'schedule' ||
      github.event.inputs.services == 'fdr' || github.event.inputs.services == 'all'
    uses: ./.github/workflows/fdr-tests.yml
    secrets: inherit

  deploy:
    needs: [trigger_wisp, trigger_fdr]
    uses: ./.github/workflows/deploy-test-report.yml
    secrets: inherit
