name: Release

on:
  push:
    branches:
      - main
      - PQ-696-get-product-version-for-data-ingestion

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@83c71bb5e316c2ffdea47a2c169498dfa9fc6afd # v7
        with:
          initial_version: 1.0.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: steps.tag_version.outputs.new_tag != ''
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          prerelease: ${{ steps.tag_version.outputs.prerelease == 'true' }}
