name: Run Behave Tests

on:
  schedule:
    - cron: '0 9 * * *'  # Esegue ogni giorno alle 9:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: Run Integration Tests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: src/automation-test
          test-output-name: results.txt
  
  notify:
    needs: [ integration_test ]
    runs-on: ubuntu-latest
    name: Notify

    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2
        with:
          status: ${{ needs.integration_test.result }}
          #token: ${{ secrets.GITHUB_TOKEN }}
          #notify_when: 'failure'
          icon_success: "white_check_mark"
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} <{workflow_url}|{workflow}> {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
