name: Run Behave Tests

on:
  schedule:
    - cron: '0 1 * * *'  # Esegue ogni giorno alle 01:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente il workflow
    inputs:
      environment:
        description: "Select the target environment"
        required: false
        default: uat
        type: choice
        options:
          - dev
          - uat

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: Run Integration Tests

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 #v5.2.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Load secrets'
        run: echo "$SECRETS" >> ./config/.secrets.yaml

      - name: 'Run tests with Behave'
        run: |
          echo "Running tests in ${{ github.event.inputs.environment }} environment"
          python3 -m behave --tags=@runnable -v
        env:
          TARGET_ENV: ${{ github.event.inputs.environment }}
