name: Run Behave Tests

on:
  schedule:
    - cron: '0 1 * * *'  # Esegue ogni giorno alle 01:00 UTC
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  Integration_test:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 #v5.2.0
        with:
          python-version: 3.x
      - name: Set up JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          distribution: zulu
          java-version: 17
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Load secrets'
        run: |
          echo "$SECRETS" >> ./config/.secrets.yaml
        env:
          SECRETS: ${{ secrets.INTEGRATION_TESTS_SECRETS }}
        id: load_secrets
      - name: 'Run tests with Behave'
        run: |
          behave --tags=@runnable --format allure_behave.formatter:AllureFormatter -o results --junit-directory=junit --junit --summary --show-timings -v
      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y
      - name: Generate test report
        run: allure generate results -o reports --clean
      - name: Store Behave report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: behave-report
          path: reports

  Display_test_report:
    runs-on: ubuntu-latest
    needs: [ Integration_test ]
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: behave-report
          path: doc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
