name: "Send notification"

on:
  workflow_call:
    inputs:
      CVE_CRITICAL:
        required: false
        type: string
      CVE_HIGH:
        required: false
        type: string
      CVE_MEDIUM:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  Notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d #v2.0.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "[ ${{ github.event.repository.name }} ]"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " https://pagopa.github.io/pagopa-platform-integration-test/integration-tests |See details on GitHub>"
                  }
                }
              ]
            }
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger